import { Inter } from "next/font/google";
import Script from "next/script";

import { Footer } from "@/components/footer";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "TinyPNG Clone 1:1"
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <main>{children}</main>
        <Footer />
      </body>

      <Script
        type="text/javascript"
        src="https://www.dropbox.com/static/api/2/dropins.js"
        id="dropboxjs"
        data-app-key={process.env.DROPBOX_APP_KEY}
      />
    </html>
  );
};

export default RootLayout;
